### ISSUE TITLE
Charts URL is getting kubernetes service name

### ISSUE THREAD

**Issue by amanscollection** [daemonza/helmet#1]
Hi,

First of all thanks for this HELMET.
I am using helmet chart and deployed it on kubernetes cluster.
I am facing an issue that in helmet-index.yaml, The value of URL of chart is 
"http://kissing-zorse-helmet-cha:1323/charts/abc-0.1.0.tgz" which is not resolvable and helm install failed.
Is there any way we can provide our own URL where these charts are actually accessible?

**Comment by kfirstri** [comment]
hi @amanscollection ,
If you want to change the chart URL you can go to this line:

https://github.com/daemonza/helmet/blob/54d5109a6ed09f51863065cb75d6ea4e3ebf5cb2/helmet-chart/templates/deployment.yaml#L23


And change it to whatever value you want, then pack and install the chart.

btw, maybe this url paramter should move to .Values ...

**Comment by amanscollection** [comment]
thanks kfirstri.
